apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "nelm-helm-controller.labels" . | nindent 4 }}
  name: {{ include "nelm-operator.fullname" . }}-bucket-viewer-role
rules:
- apiGroups:
  - source.werf.io
  resources:
  - buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.werf.io
  resources:
  - buckets/status
  verbs:
  - get
