---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "nelm-operator.labels" . | nindent 4 }}
  name: {{ include "nelm-operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - helm.werf.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.werf.io
  resources:
  - helmreleases/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - helm.werf.io
  resources:
  - helmreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.werf.io
  resources:
  - helmcharts
  - ocirepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.werf.io
  resources:
  - helmcharts/status
  - ocirepositories/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - source.werf.io
  resources:
  - buckets
  - gitrepositories
  - helmcharts
  - helmrepositories
  - ocirepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.werf.io
  resources:
  - buckets/finalizers
  - gitrepositories/finalizers
  - helmcharts/finalizers
  - helmrepositories/finalizers
  - ocirepositories/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - source.werf.io
  resources:
  - buckets/status
  - gitrepositories/status
  - helmcharts/status
  - helmrepositories/status
  - ocirepositories/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "nelm-helm-controller.labels" . | nindent 4 }}
  name: {{ include "nelm-operator.fullname" . }}-reconciler-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
