---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nelm-controller.fullname" . }}-manager-role
  labels:
    {{- include "nelm-controller.labels" . | nindent 4 }}
rules:
# TODO: remove below group after default service account implementation.
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
# TODO: remove below group after default service account and impresonation will be implemented.
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - nelm.werf.io
  resources:
  - releases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nelm.werf.io
  resources:
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - nelm.werf.io
  resources:
  - releases/status
  verbs:
  - get
  - patch
  - update
# NOTE: this required to manage inline chart definitions.
# TODO: implement below group generation by using kubebuilder annotations.
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - gitrepositories
  - helmcharts
  - helmrepositories
  - ocirepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# TODO: implement below group generation by using kubebuilder annotations.
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
