apiVersion: nelm.werf.io/v1alpha1
kind: Release
metadata:
  labels:
    app.kubernetes.io/name: nelm-operator
    app.kubernetes.io/managed-by: kustomize
  name: release-sample
spec:
  interval: 5m
  chart:
    repo:
      url: https://stefanprodan.github.io/podinfo
      name: podinfo
      version: "6.7.1"
      interval: 5m
  values:
    replicaCount: 1
  install:
    autoRollback: true
    retries: 3
  tracking:
    readinessTimeout: 5m
