apiVersion: v2
appVersion: v0.0.1 # x-release-please-version
description: A Helm chart for nelm controller
name: nelm-controller
sources:
  - https://github.com/werf/nelm-operator/tree/main/charts/nelm-controller
type: application
version: 0.0.1 # x-release-please-version
