apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluxcd-source-controller.fullname" . }}-helmchart-editor-role
  labels:
    {{- include "fluxcd-source-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts/status
  verbs:
  - get
